#imagem basica
FROM nginx
#Comentario sobre que fez a imagem 
MAINTAINER "Mutant S/A"

#Determina o volume de trabalho do container
WORKDIR /volumeHost

#copie tudo que esta no diretorio host (sua maquina) para o diretorio do container /volumeHost
COPY . /volumeHost

